### ISSUE TITLE
Issues with the example

### ISSUE THREAD

**Issue by Biribu** [luanguimaraesla/mqttsn#1]
Hi,
I rewrite this issue. I just installed python 3.6 to include F property and also reinstall this library.

I get this issue while executing:

Traceback (most recent call last):
  File "simple.py", line 16, in <module>
    aclient.connect()
  File "/usr/local/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/client.py", line 134, in connect
    self.sock.send(connect.pack())
  File "/usr/local/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/lib/connects.py", line 22, in pack
    buffer += self.client_id
TypeError: can't concat str to bytes

**Comment by davidg238** [comment]
If you omit the Client.id argument, so that a guid is used, you get further.
Failed for me as:

(envLacerda) david@dv6-1355dx:\~/mqttsn/examples$ python simple.py  
topic id for topic1 is 1  
topic id for topic2 is 2  
PUBLISH: length 0, PUBLISH, flags < dup False, qos 0, retain False, will False, clean_session True, topic_id_type 0 >, topic_id 1, msg_id 0, data aaaa
PAYLOAD LEN: 4
BUFFER: b'\x0b\x0c\x04\x00\x01\x00\x00aaaa'
PUBLISH: length 0, PUBLISH, flags < dup False, qos 0, retain False, will False, clean_session True, topic_id_type 0 >, topic_id 2, msg_id 0, data bbbb
PAYLOAD LEN: 4
BUFFER: b'\x0b\x0c\x04\x00\x02\x00\x00bbbb'
Unexpected exception (<class 'AttributeError'>, AttributeError("'str' object has no attribute 'decode'",), <traceback object at 0x7f33c33876c8>)
Traceback (most recent call last):
  File "/home/david/envLacerda/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/internal.py", line 114, in __call__
    self.receive(callback)
  File "/home/david/envLacerda/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/internal.py", line 105, in receive
    self._actions[packet.mh.msg_type](packet, callback, address)
  File "/home/david/envLacerda/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/internal.py", line 186, in _process_publish
    topicname = packet.topic_name.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
PUBLISH: length 0, PUBLISH, flags < dup False, qos 0, retain False, will False, clean_session True, topic_id_type 0 >, topic_id 2, msg_id 0, data cccc
PAYLOAD LEN: 4
BUFFER: b'\x0b\x0c\x04\x00\x02\x00\x00cccc'
PUBLISH: length 0, PUBLISH, flags < dup False, qos 0, retain False, will False, clean_session True, topic_id_type 0 >, topic_id 1, msg_id 0, data dddd
PAYLOAD LEN: 4
BUFFER: b'\x0b\x0c\x04\x00\x01\x00\x00dddd'
Traceback (most recent call last):
  File "simple.py", line 34, in <module>
    aclient.disconnect()
  File "/home/david/envLacerda/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/client.py", line 228, in disconnect
    self.sock.send(disconnect.pack())
  File "/home/david/envLacerda/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/lib/disconnects.py", line 18, in pack
    buf = self.mh.pack(0)
  File "/home/david/envLacerda/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/lib/message_headers.py", line 31, in pack
    buffer = self.encode_length(bufferlen) + chr_(self.msg_type)
  File "/home/david/envLacerda/lib/python3.6/site-packages/mqttsn-0.0.4-py3.6.egg/mqttsn/lib/message_headers.py", line 57, in encode_length
    raise "Invalid buffer size"
TypeError: exceptions must derive from BaseException
(envLacerda) david@dv6-1355dx:~/mqttsn/examples$

**Comment by davidg238** [comment]
In internal.py, in  _processs_publish()    you change the line  
topicname = packet.topic_name.decode('utf-8')     to  
topicname = packet.topic_name

in  unsubscribes.py  in class Unsubscribes(), pack(), you change the 2 lines
buffer += bytes(self.topic_name.encode('utf-8'))   to  
buffer += bytes(self.topic_name, 'utf-8')  

you fail on the aclient.disconnect() of  simple.py .  

Looking at the console of the rsmb server, some of the messages sent appear to have "extra" characters, so there are likely other packet encoding issues.
I am learning Python, but these issues appear to be from the changes from Python 2 to 3?

**Comment by bhctsntrk** [comment]
In the latest version that I get from PyPI there is an error in

mqttsn/lib/connects.py", line 22
TypeError: can't concat str to bytes

``` python
buffer += self.client_id  # I changed this to
buffer += self.client_id.encode()  # This
```
and worked.
